//
//  EthereumKeyManager.swift
//  Sur
//
//  Manages Ethereum key derivation and address generation following BIP-32/BIP-44 standards.
//
//  This implementation uses:
//  - secp256k1 elliptic curve for key generation (same as MetaMask, Ledger, etc.)
//  - Keccak-256 hashing for Ethereum address derivation (not SHA3-256)
//  - BIP-44 derivation path: m/44'/60'/0'/0/{index}
//
//  The addresses generated by this implementation match those produced by MetaMask
//  when using the same mnemonic/seed and account index.
//

import Foundation
import CryptoKit

/// Error types for Ethereum key operations
enum EthereumKeyError: LocalizedError {
    case invalidSeed
    case derivationFailed
    case invalidPrivateKey
    case invalidPublicKey
    case addressGenerationFailed
    
    var errorDescription: String? {
        switch self {
        case .invalidSeed:
            return "Invalid seed data for key derivation"
        case .derivationFailed:
            return "Failed to derive key"
        case .invalidPrivateKey:
            return "Invalid private key"
        case .invalidPublicKey:
            return "Invalid public key"
        case .addressGenerationFailed:
            return "Failed to generate Ethereum address"
        }
    }
}

/// Manages Ethereum key derivation following BIP-32/BIP-44 standards
///
/// This implementation produces addresses compatible with MetaMask by using:
/// - secp256k1 curve for public key derivation (via Secp256k1.swift)
/// - Keccak-256 hash function for address generation (via Keccak256.swift)
/// - BIP-44 derivation path: m/44'/60'/0'/0/{index}
final class EthereumKeyManager {
    
    // MARK: - Constants
    
    /// BIP-44 derivation path for Ethereum: m/44'/60'/0'/0/0
    /// Reference: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
    private static let ethereumDerivationPath = "m/44'/60'/0'/0/0"
    
    /// Hardened key offset (2^31) for BIP-32 derivation
    private static let hardenedOffset: UInt32 = 0x80000000
    
    // MARK: - Public Methods
    
    /// Derive private key from mnemonic seed following BIP-44 path for Ethereum
    /// - Parameters:
    ///   - seed: 64-byte seed from mnemonic (BIP-39)
    ///   - index: Account index for BIP-44 path (default 0)
    /// - Returns: 32-byte private key
    static func derivePrivateKey(from seed: Data, index: UInt32 = 0) throws -> Data {
        guard seed.count == 64 else {
            throw EthereumKeyError.invalidSeed
        }
        
        // Create master key from seed using HMAC-SHA512 (BIP-32)
        let masterKey = try deriveMasterKey(from: seed)
        
        // Derive child keys following BIP-44 path: m/44'/60'/0'/0/{index}
        // Each component with ' is hardened (add 0x80000000)
        let path: [UInt32] = [
            44 + hardenedOffset,    // purpose (hardened)
            60 + hardenedOffset,    // coin_type for Ethereum (hardened)
            0 + hardenedOffset,     // account (hardened)
            0,                       // change (external chain)
            index                    // address_index
        ]
        
        let derivedKey = try deriveKeyAtPath(
            masterPrivateKey: masterKey.privateKey,
            masterChainCode: masterKey.chainCode,
            path: path
        )
        
        guard derivedKey.privateKey.count == 32 else {
            throw EthereumKeyError.derivationFailed
        }
        
        // Validate the derived key is valid for secp256k1
        guard Secp256k1.isValidPrivateKey(derivedKey.privateKey) else {
            throw EthereumKeyError.invalidPrivateKey
        }
        
        return derivedKey.privateKey
    }
    
    /// Generate Ethereum public address from private key
    ///
    /// Uses secp256k1 curve for public key derivation and Keccak-256 for address generation.
    /// This produces addresses compatible with MetaMask and other Ethereum wallets.
    ///
    /// - Parameter privateKey: 32-byte private key
    /// - Returns: Ethereum address string with 0x prefix (EIP-55 checksummed)
    static func generateAddress(from privateKey: Data) throws -> String {
        guard privateKey.count == 32 else {
            throw EthereumKeyError.invalidPrivateKey
        }
        
        // Generate uncompressed public key using secp256k1 curve
        guard let publicKey = Secp256k1.derivePublicKey(from: privateKey) else {
            throw EthereumKeyError.invalidPublicKey
        }
        
        // Generate address from public key using Keccak-256
        let address = try generateAddressFromPublicKey(publicKey)
        
        return address
    }
    
    /// Generate both keys and address from mnemonic
    /// - Parameters:
    ///   - mnemonic: BIP-39 mnemonic phrase
    ///   - index: Account index for BIP-44 path (default 0)
    /// - Returns: Tuple of (privateKey, publicAddress)
    static func generateKeysFromMnemonic(_ mnemonic: String, index: UInt32 = 0) throws -> (privateKey: Data, address: String) {
        // Convert mnemonic to seed using BIP-39
        let seed = try MnemonicGenerator.mnemonicToSeed(mnemonic)
        
        // Derive private key following BIP-44 path
        let privateKey = try derivePrivateKey(from: seed, index: index)
        
        // Generate checksummed Ethereum address
        let address = try generateAddress(from: privateKey)
        
        return (privateKey, address)
    }
    
    /// Format Ethereum address with checksum (EIP-55)
    ///
    /// EIP-55 uses Keccak-256 hash of the lowercase address to determine
    /// which characters should be uppercase.
    ///
    /// - Parameter address: Lowercase address without 0x prefix
    /// - Returns: Checksummed address with 0x prefix
    static func checksumAddress(_ address: String) -> String {
        let cleanAddress = address.lowercased().hasPrefix("0x")
            ? String(address.dropFirst(2)).lowercased()
            : address.lowercased()
        
        // Hash the lowercase address using Keccak-256 (EIP-55 requirement)
        guard let addressData = cleanAddress.data(using: .utf8) else {
            return "0x" + cleanAddress
        }
        let hash = Keccak256.hash(addressData)
        let hashHex = hash.map { String(format: "%02x", $0) }.joined()
        
        // Apply checksum: uppercase if corresponding hash nibble >= 8
        var checksummed = "0x"
        for (index, char) in cleanAddress.enumerated() {
            if char.isLetter {
                let hashChar = hashHex[hashHex.index(hashHex.startIndex, offsetBy: index)]
                if let hashValue = Int(String(hashChar), radix: 16), hashValue >= 8 {
                    checksummed.append(char.uppercased())
                } else {
                    checksummed.append(char)
                }
            } else {
                checksummed.append(char)
            }
        }
        
        return checksummed
    }
    
    /// Shorten address for display (e.g., "0x1234...5678")
    /// - Parameter address: Full Ethereum address
    /// - Returns: Shortened address string
    static func shortenAddress(_ address: String) -> String {
        guard address.count >= 10 else { return address }
        let prefix = String(address.prefix(6))
        let suffix = String(address.suffix(4))
        return "\(prefix)...\(suffix)"
    }
    
    // MARK: - Private Methods
    
    /// Derive master key from seed using HMAC-SHA512 (BIP-32)
    private static func deriveMasterKey(from seed: Data) throws -> (privateKey: Data, chainCode: Data) {
        // Use "Bitcoin seed" as the key for HMAC (BIP-32 standard)
        let key = "Bitcoin seed".data(using: .utf8)!
        
        // HMAC-SHA512
        let hmac = HMAC<SHA512>.authenticationCode(for: seed, using: SymmetricKey(data: key))
        let hmacData = Data(hmac)
        
        // First 32 bytes are the private key
        let privateKey = Data(hmacData.prefix(32))
        
        // Last 32 bytes are the chain code
        let chainCode = Data(hmacData.suffix(32))
        
        // Validate private key is valid for secp256k1
        guard Secp256k1.isValidPrivateKey(privateKey) else {
            throw EthereumKeyError.derivationFailed
        }
        
        return (privateKey, chainCode)
    }
    
    /// Derive child key at a given BIP-32/BIP-44 path
    /// - Parameters:
    ///   - masterPrivateKey: 32-byte master private key
    ///   - masterChainCode: 32-byte master chain code
    ///   - path: Array of path indices (hardened indices have 0x80000000 added)
    /// - Returns: Derived private key and chain code
    private static func deriveKeyAtPath(
        masterPrivateKey: Data,
        masterChainCode: Data,
        path: [UInt32]
    ) throws -> (privateKey: Data, chainCode: Data) {
        var currentKey = masterPrivateKey
        var currentChainCode = masterChainCode
        
        for index in path {
            let isHardened = index >= hardenedOffset
            
            // Derive child key
            let (childKey, childChainCode) = try deriveChildKey(
                parentPrivateKey: currentKey,
                parentChainCode: currentChainCode,
                index: index,
                hardened: isHardened
            )
            
            currentKey = childKey
            currentChainCode = childChainCode
        }
        
        return (currentKey, currentChainCode)
    }
    
    /// Derive a single child key (BIP-32)
    private static func deriveChildKey(
        parentPrivateKey: Data,
        parentChainCode: Data,
        index: UInt32,
        hardened: Bool
    ) throws -> (privateKey: Data, chainCode: Data) {
        var data = Data()
        
        if hardened {
            // Hardened child: 0x00 || parent_private_key || index
            data.append(0x00)
            data.append(parentPrivateKey)
        } else {
            // Normal child: parent_public_key (compressed) || index
            guard let compressedPublicKey = Secp256k1.deriveCompressedPublicKey(from: parentPrivateKey) else {
                throw EthereumKeyError.invalidPublicKey
            }
            data.append(compressedPublicKey)
        }
        
        // Append index as big-endian 4 bytes
        var indexBE = index.bigEndian
        data.append(Data(bytes: &indexBE, count: 4))
        
        // HMAC-SHA512
        let hmac = HMAC<SHA512>.authenticationCode(
            for: data,
            using: SymmetricKey(data: parentChainCode)
        )
        let hmacData = Data(hmac)
        
        // First 32 bytes for key derivation
        let keyData = Data(hmacData.prefix(32))
        
        // Last 32 bytes are the new chain code
        let childChainCode = Data(hmacData.suffix(32))
        
        // Add parent key to derived key (mod n for secp256k1)
        let childKey = addPrivateKeys(parentPrivateKey, keyData)
        
        guard Secp256k1.isValidPrivateKey(childKey) else {
            throw EthereumKeyError.derivationFailed
        }
        
        return (childKey, childChainCode)
    }
    
    /// Add two private keys together (mod curve order n)
    /// This implements the BIP-32 child key derivation formula: child = (parent + tweak) mod n
    /// Returns the sum modulo the curve order, which is guaranteed to be a valid private key
    /// as long as it's non-zero (zero would indicate an extremely rare edge case)
    private static func addPrivateKeys(_ key1: Data, _ key2: Data) -> Data {
        return Secp256k1.addModN(key1, key2)
    }
    
    /// Generate Ethereum address from uncompressed public key using Keccak-256
    ///
    /// Ethereum address derivation:
    /// 1. Take the uncompressed public key (65 bytes: 0x04 + X + Y)
    /// 2. Hash the X and Y coordinates (64 bytes, excluding 0x04 prefix) with Keccak-256
    /// 3. Take the last 20 bytes of the hash
    /// 4. Apply EIP-55 checksum
    ///
    /// - Parameter publicKey: 65-byte uncompressed public key
    /// - Returns: Checksummed Ethereum address with 0x prefix
    private static func generateAddressFromPublicKey(_ publicKey: Data) throws -> String {
        // Uncompressed public key format: 0x04 + X (32 bytes) + Y (32 bytes) = 65 bytes
        guard publicKey.count == 65 && publicKey[0] == 0x04 else {
            throw EthereumKeyError.invalidPublicKey
        }
        
        // Hash the public key (excluding the 0x04 prefix)
        // Ethereum uses only the X and Y coordinates (64 bytes)
        let publicKeyToHash = Data(publicKey.dropFirst())
        
        // Keccak-256 hash (NOT SHA3-256, Ethereum uses original Keccak)
        let hash = Keccak256.hash(publicKeyToHash)
        
        // Take last 20 bytes as the address
        let addressBytes = hash.suffix(20)
        
        // Convert to hex string
        let addressHex = addressBytes.map { String(format: "%02x", $0) }.joined()
        
        // Return EIP-55 checksummed address
        return checksumAddress(addressHex)
    }
}
