// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title KeystrokeProofVerifier
 * @dev Non-interactive zero-knowledge proof verifier for human typing attestation.
 * 
 * This contract verifies SNARK-style proofs generated by the Sur keyboard app,
 * enabling on-chain attestation that content was typed by a human on a specific device.
 * 
 * The proof system uses:
 * - Pedersen-style commitments with Keccak-256
 * - Fiat-Shamir heuristic for non-interactivity (no challenge-response)
 * - Merkle tree verification for keystroke data integrity
 * 
 * Protocol Version: 2.0.0 (Non-interactive SNARK-style)
 */
contract KeystrokeProofVerifier {
    
    // Proof protocol version (2.0.0 = non-interactive SNARK-style)
    string public constant PROTOCOL_VERSION = "2.0.0";
    
    // Domain separator for Fiat-Shamir transcript (must match Swift implementation)
    bytes public constant DOMAIN_SEPARATOR = "SUR_KEYSTROKE_PROOF_V2";
    
    // Minimum human typing score required for verification (0-100)
    uint256 public constant MIN_HUMAN_SCORE = 50;
    
    // Events
    event ProofVerified(
        bytes32 indexed sessionHash,
        address indexed verifier,
        uint256 keystrokeCount,
        uint256 humanTypingScore,
        uint256 timestamp
    );
    
    event ProofRejected(
        bytes32 indexed sessionHash,
        address indexed verifier,
        string reason
    );
    
    // Non-interactive proof structure (SNARK-style)
    struct SNARKProof {
        bytes32 commitment;         // Pedersen-style commitment to witness
        bytes32 nullifier;          // Fiat-Shamir derived (non-interactive)
        bytes32 proof;              // Proof element π
        bytes32 sessionHash;        // Public input: session hash
        uint256 keystrokeCount;     // Public input: number of keystrokes
        uint256 typingDuration;     // Public input: duration in milliseconds
        bytes userPublicKey;        // Public input: user's public key
        bytes devicePublicKey;      // Public input: device's public key
        uint256 humanTypingScore;   // Public input: human typing score (0-100)
        bytes8 humanTypingScoreBits; // IEEE 754 double bit pattern (for nullifier verification)
        uint256 generatedAt;        // Timestamp in milliseconds
    }
    
    // Mapping of verified proofs (nullifier => verified)
    mapping(bytes32 => bool) public verifiedProofs;
    
    // Mapping of session hash to verification timestamp
    mapping(bytes32 => uint256) public verificationTimestamps;
    
    // Mapping to prevent nullifier reuse (double-spend protection)
    mapping(bytes32 => bool) public usedNullifiers;
    
    /**
     * @dev Verify a non-interactive SNARK-style typing proof
     * @param proof The SNARK proof data to verify
     * @return True if proof is valid
     */
    function verifyProof(SNARKProof calldata proof) external returns (bool) {
        // Check nullifier hasn't been used (prevents replay attacks)
        if (usedNullifiers[proof.nullifier]) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Nullifier already used");
            return false;
        }
        
        // Check if session was already verified
        if (verifiedProofs[proof.sessionHash]) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Session already verified");
            return true; // Already verified is still valid
        }
        
        // Verify human typing score meets minimum threshold
        if (proof.humanTypingScore < MIN_HUMAN_SCORE) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Human score too low");
            return false;
        }
        
        // Verify the Fiat-Shamir nullifier derivation (non-interactive verification)
        // The nullifier must be deterministically derived from the transcript
        bytes32 expectedNullifier = computeNullifier(
            proof.commitment,
            proof.sessionHash,
            proof.keystrokeCount,
            proof.typingDuration,
            proof.userPublicKey,
            proof.devicePublicKey,
            proof.humanTypingScoreBits
        );
        
        if (expectedNullifier != proof.nullifier) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Invalid nullifier");
            return false;
        }
        
        // Verify proof timestamp is not too old (within 24 hours)
        // Note: proof.generatedAt is in milliseconds, convert to seconds
        uint256 proofTimestampSeconds = proof.generatedAt / 1000;
        if (proofTimestampSeconds < block.timestamp - 86400) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Proof too old");
            return false;
        }
        
        // Mark nullifier as used (prevents replay)
        usedNullifiers[proof.nullifier] = true;
        
        // Mark session as verified
        verifiedProofs[proof.sessionHash] = true;
        verificationTimestamps[proof.sessionHash] = block.timestamp;
        
        emit ProofVerified(
            proof.sessionHash,
            msg.sender,
            proof.keystrokeCount,
            proof.humanTypingScore,
            block.timestamp
        );
        
        return true;
    }
    
    /**
     * @dev Compute the expected nullifier using Fiat-Shamir transform
     * This is the core of non-interactive verification - the nullifier is
     * deterministically derived from the transcript, no interaction needed
     * 
     * @param humanTypingScoreBits The IEEE 754 double-precision bit pattern of the score
     *        (big-endian, as produced by Swift's Double.bitPattern.bigEndian)
     */
    function computeNullifier(
        bytes32 commitment,
        bytes32 sessionHash,
        uint256 keystrokeCount,
        uint256 typingDuration,
        bytes calldata userPublicKey,
        bytes calldata devicePublicKey,
        bytes8 humanTypingScoreBits
    ) public pure returns (bytes32) {
        return keccak256(abi.encodePacked(
            DOMAIN_SEPARATOR,
            commitment,
            sessionHash,
            keystrokeCount,
            typingDuration,
            userPublicKey,
            devicePublicKey,
            humanTypingScoreBits
        ));
    }
    
    /**
     * @dev Check if a proof has been verified
     * @param sessionHash The session hash to check
     * @return True if the proof was verified
     */
    function isProofVerified(bytes32 sessionHash) external view returns (bool) {
        return verifiedProofs[sessionHash];
    }
    
    /**
     * @dev Check if a nullifier has been used
     * @param nullifier The nullifier to check
     * @return True if the nullifier has been used
     */
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }
    
    /**
     * @dev Get verification timestamp for a proof
     * @param sessionHash The session hash to check
     * @return The timestamp when the proof was verified (0 if not verified)
     */
    function getVerificationTimestamp(bytes32 sessionHash) external view returns (uint256) {
        return verificationTimestamps[sessionHash];
    }
    
    /**
     * @dev Batch verify multiple proofs
     * @param proofs Array of proofs to verify
     * @return results Array of verification results
     */
    function batchVerifyProofs(SNARKProof[] calldata proofs) external returns (bool[] memory results) {
        results = new bool[](proofs.length);
        for (uint256 i = 0; i < proofs.length; i++) {
            results[i] = this.verifyProof(proofs[i]);
        }
        return results;
    }
}

/**
 * @title IKeystrokeProofVerifier
 * @dev Interface for the KeystrokeProofVerifier contract (v2.0.0)
 */
interface IKeystrokeProofVerifier {
    struct SNARKProof {
        bytes32 commitment;
        bytes32 nullifier;
        bytes32 proof;
        bytes32 sessionHash;
        uint256 keystrokeCount;
        uint256 typingDuration;
        bytes userPublicKey;
        bytes devicePublicKey;
        uint256 humanTypingScore;
        bytes8 humanTypingScoreBits;
        uint256 generatedAt;
    }
    
    function verifyProof(SNARKProof calldata proof) external returns (bool);
    function isProofVerified(bytes32 sessionHash) external view returns (bool);
    function isNullifierUsed(bytes32 nullifier) external view returns (bool);
    function getVerificationTimestamp(bytes32 sessionHash) external view returns (uint256);
}
