// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title KeystrokeProofVerifier
 * @dev Verifies zero-knowledge proofs of human typing from the Sur keyboard app.
 * 
 * This contract allows verification of typing proofs generated by the Sur app,
 * enabling on-chain attestation that content was typed by a human on a specific device.
 */
contract KeystrokeProofVerifier {
    
    // Proof protocol version
    string public constant PROTOCOL_VERSION = "1.0.0";
    
    // Minimum human typing score required for verification (0-100)
    uint256 public constant MIN_HUMAN_SCORE = 50;
    
    // Events
    event ProofVerified(
        bytes32 indexed sessionHash,
        address indexed verifier,
        uint256 keystrokeCount,
        uint256 humanTypingScore,
        uint256 timestamp
    );
    
    event ProofRejected(
        bytes32 indexed sessionHash,
        address indexed verifier,
        string reason
    );
    
    // Struct for proof data
    struct TypingProof {
        bytes32 commitment;
        bytes32 challenge;
        bytes32 response;
        bytes32 sessionHash;
        uint256 keystrokeCount;
        uint256 typingDuration;
        bytes userPublicKey;
        bytes devicePublicKey;
        uint256 humanTypingScore;
        uint256 generatedAt;
    }
    
    // Mapping of verified proofs
    mapping(bytes32 => bool) public verifiedProofs;
    
    // Mapping of session hash to verification timestamp
    mapping(bytes32 => uint256) public verificationTimestamps;
    
    /**
     * @dev Verify a typing proof
     * @param proof The proof data to verify
     * @return True if proof is valid
     */
    function verifyProof(TypingProof calldata proof) external returns (bool) {
        // Check if proof was already verified
        if (verifiedProofs[proof.sessionHash]) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Already verified");
            return true; // Already verified is still valid
        }
        
        // Verify human typing score meets minimum threshold
        if (proof.humanTypingScore < MIN_HUMAN_SCORE) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Human score too low");
            return false;
        }
        
        // Verify challenge derivation
        bytes32 expectedChallenge = keccak256(abi.encodePacked(
            proof.commitment,
            proof.sessionHash,
            proof.keystrokeCount,
            proof.typingDuration,
            proof.userPublicKey,
            proof.devicePublicKey
        ));
        
        if (expectedChallenge != proof.challenge) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Invalid challenge");
            return false;
        }
        
        // Verify proof timestamp is not too old (within 24 hours)
        // Note: proof.generatedAt is in milliseconds (from Swift), convert to seconds for comparison
        // This check prevents replay attacks with old proofs
        uint256 proofTimestampSeconds = proof.generatedAt / 1000;
        if (proofTimestampSeconds < block.timestamp - 86400) {
            emit ProofRejected(proof.sessionHash, msg.sender, "Proof too old");
            return false;
        }
        
        // Mark as verified
        verifiedProofs[proof.sessionHash] = true;
        verificationTimestamps[proof.sessionHash] = block.timestamp;
        
        emit ProofVerified(
            proof.sessionHash,
            msg.sender,
            proof.keystrokeCount,
            proof.humanTypingScore,
            block.timestamp
        );
        
        return true;
    }
    
    /**
     * @dev Check if a proof has been verified
     * @param sessionHash The session hash to check
     * @return True if the proof was verified
     */
    function isProofVerified(bytes32 sessionHash) external view returns (bool) {
        return verifiedProofs[sessionHash];
    }
    
    /**
     * @dev Get verification timestamp for a proof
     * @param sessionHash The session hash to check
     * @return The timestamp when the proof was verified (0 if not verified)
     */
    function getVerificationTimestamp(bytes32 sessionHash) external view returns (uint256) {
        return verificationTimestamps[sessionHash];
    }
    
    /**
     * @dev Batch verify multiple proofs
     * @param proofs Array of proofs to verify
     * @return results Array of verification results
     */
    function batchVerifyProofs(TypingProof[] calldata proofs) external returns (bool[] memory results) {
        results = new bool[](proofs.length);
        for (uint256 i = 0; i < proofs.length; i++) {
            results[i] = this.verifyProof(proofs[i]);
        }
        return results;
    }
    
    /**
     * @dev Compute the expected challenge for verification
     * @param commitment The proof commitment
     * @param sessionHash The session hash
     * @param keystrokeCount Number of keystrokes
     * @param typingDuration Duration in milliseconds
     * @param userPublicKey User's public key
     * @param devicePublicKey Device's public key
     * @return The expected challenge hash
     */
    function computeChallenge(
        bytes32 commitment,
        bytes32 sessionHash,
        uint256 keystrokeCount,
        uint256 typingDuration,
        bytes calldata userPublicKey,
        bytes calldata devicePublicKey
    ) external pure returns (bytes32) {
        return keccak256(abi.encodePacked(
            commitment,
            sessionHash,
            keystrokeCount,
            typingDuration,
            userPublicKey,
            devicePublicKey
        ));
    }
}

/**
 * @title IKeystrokeProofVerifier
 * @dev Interface for the KeystrokeProofVerifier contract
 */
interface IKeystrokeProofVerifier {
    struct TypingProof {
        bytes32 commitment;
        bytes32 challenge;
        bytes32 response;
        bytes32 sessionHash;
        uint256 keystrokeCount;
        uint256 typingDuration;
        bytes userPublicKey;
        bytes devicePublicKey;
        uint256 humanTypingScore;
        uint256 generatedAt;
    }
    
    function verifyProof(TypingProof calldata proof) external returns (bool);
    function isProofVerified(bytes32 sessionHash) external view returns (bool);
    function getVerificationTimestamp(bytes32 sessionHash) external view returns (uint256);
}
