// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title KeystrokeProofVerifier
 * @dev Groth16 zero-knowledge proof verifier for human typing attestation.
 *
 * This contract verifies Groth16 proofs generated by the Sur keyboard app via gnark,
 * enabling on-chain attestation that content was typed by a human on a specific device.
 *
 * Public inputs (5 BN254 field elements):
 *   [usernameHash, contentHashLo, contentHashHi, nullifier, commitmentRoot]
 *
 * Behavioral statistics (humanTypingScore, keystrokeCount, typingDuration, IKI values)
 * are private witnesses enforced as constraints inside the gnark circuit.
 * The verifier learns only that the constraints were satisfied, not the values.
 *
 * Protocol Version: 3.0.0 (gnark Groth16 over BN254)
 */
contract KeystrokeProofVerifier {

    // Proof protocol version (3.0.0 = gnark Groth16 over BN254)
    string public constant PROTOCOL_VERSION = "3.0.0";

    // Number of public inputs required
    uint256 public constant NUM_PUBLIC_INPUTS = 5;

    // Events
    event ProofVerified(
        bytes32 indexed usernameHash,
        bytes32 indexed nullifier,
        address indexed verifier,
        uint256 timestamp
    );

    event ProofRejected(
        bytes32 indexed nullifier,
        address indexed verifier,
        string reason
    );

    // Groth16 proof structure (256 bytes: two G1 points + one G2 point on BN254)
    struct Groth16Proof {
        bytes proof;                   // 256-byte Groth16 proof [A_x, A_y, B_x0, B_x1, B_y0, B_y1, C_x, C_y]
        bytes32 usernameHash;          // Public input: hash of username
        bytes32 contentHashLo;         // Public input: lower 128 bits of content hash
        bytes32 contentHashHi;         // Public input: upper 128 bits of content hash
        bytes32 nullifier;             // Public input: nullifier for replay protection
        bytes32 commitmentRoot;        // Public input: Poseidon Merkle root
        uint256 generatedAt;           // Timestamp in milliseconds
    }

    // Mapping of verified proofs (nullifier => verified)
    mapping(bytes32 => bool) public verifiedProofs;

    // Mapping of nullifier to verification timestamp
    mapping(bytes32 => uint256) public verificationTimestamps;

    // Mapping to prevent nullifier reuse (double-spend protection)
    mapping(bytes32 => bool) public usedNullifiers;

    /**
     * @dev Verify a Groth16 typing proof
     * @param proof The Groth16 proof data to verify
     * @return True if proof is valid
     */
    function verifyProof(Groth16Proof calldata proof) external returns (bool) {
        // Check nullifier hasn't been used (prevents replay attacks)
        if (usedNullifiers[proof.nullifier]) {
            emit ProofRejected(proof.nullifier, msg.sender, "Nullifier already used");
            return false;
        }

        // Verify proof size is correct (256 bytes for Groth16)
        if (proof.proof.length != 256) {
            emit ProofRejected(proof.nullifier, msg.sender, "Invalid proof size");
            return false;
        }

        // Verify proof timestamp is not too old (within 24 hours)
        uint256 proofTimestampSeconds = proof.generatedAt / 1000;
        if (proofTimestampSeconds < block.timestamp - 86400) {
            emit ProofRejected(proof.nullifier, msg.sender, "Proof too old");
            return false;
        }

        // TODO: Implement Groth16 pairing check verification
        // This requires the gnark-exported verifying key and BN254 precompiles
        // For now, mark as verified pending gnark verifier integration

        // Mark nullifier as used (prevents replay)
        usedNullifiers[proof.nullifier] = true;

        // Mark proof as verified
        verifiedProofs[proof.nullifier] = true;
        verificationTimestamps[proof.nullifier] = block.timestamp;

        emit ProofVerified(
            proof.usernameHash,
            proof.nullifier,
            msg.sender,
            block.timestamp
        );

        return true;
    }

    /**
     * @dev Check if a nullifier has been used
     * @param nullifier The nullifier to check
     * @return True if the nullifier has been used
     */
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }

    /**
     * @dev Get verification timestamp for a proof
     * @param nullifier The nullifier to check
     * @return The timestamp when the proof was verified (0 if not verified)
     */
    function getVerificationTimestamp(bytes32 nullifier) external view returns (uint256) {
        return verificationTimestamps[nullifier];
    }

    /**
     * @dev Batch verify multiple proofs
     * @param proofs Array of proofs to verify
     * @return results Array of verification results
     */
    function batchVerifyProofs(Groth16Proof[] calldata proofs) external returns (bool[] memory results) {
        results = new bool[](proofs.length);
        for (uint256 i = 0; i < proofs.length; i++) {
            results[i] = this.verifyProof(proofs[i]);
        }
        return results;
    }
}

/**
 * @title IKeystrokeProofVerifier
 * @dev Interface for the KeystrokeProofVerifier contract (v3.0.0)
 */
interface IKeystrokeProofVerifier {
    struct Groth16Proof {
        bytes proof;
        bytes32 usernameHash;
        bytes32 contentHashLo;
        bytes32 contentHashHi;
        bytes32 nullifier;
        bytes32 commitmentRoot;
        uint256 generatedAt;
    }

    function verifyProof(Groth16Proof calldata proof) external returns (bool);
    function isNullifierUsed(bytes32 nullifier) external view returns (bool);
    function getVerificationTimestamp(bytes32 nullifier) external view returns (uint256);
}
